name: sistema_professores_server
description: Backend server for Sistema Para Professores
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  postgres: ^3.0.2
  mongo_dart: ^0.10.3
  dotenv: ^4.2.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
  http: ^1.2.0
  mocktail: ^1.0.0
